/**
 * Verbandslogos für den Bundler — erzeugt von
 * scripts/generate-association-logos.js. Nicht von Hand bearbeiten.
 *
 * Verbände ohne Eintrag zeigen weiterhin die Länderflagge.
 */

export const associationLogos: Record<string, number> = {
  'AFG': require('../../../assets/nations/106_nation.png'),
  'ASA': require('../../../assets/nations/129504_nation.png'),
  'AUS': require('../../../assets/nations/1435_nation.png'),
  'BAN': require('../../../assets/nations/108_nation.png'),
  'BDI': require('../../../assets/nations/10_nation.png'),
  'BHR': require('../../../assets/nations/107_nation.png'),
  'BHU': require('../../../assets/nations/131012_nation.png'),
  'CAM': require('../../../assets/nations/118_nation.png'),
  'CHN': require('../../../assets/nations/110_nation.png'),
  'CMR': require('../../../assets/nations/11_nation.png'),
  'COD': require('../../../assets/nations/103277_nation.png'),
  'CTA': require('../../../assets/nations/13_nation.png'),
  'ERI': require('../../../assets/nations/129511_nation.png'),
  'GUM': require('../../../assets/nations/129508_nation.png'),
  'HKG': require('../../../assets/nations/111_nation.png'),
  'IDN': require('../../../assets/nations/113_nation.png'),
  'IND': require('../../../assets/nations/112_nation.png'),
  'IRN': require('../../../assets/nations/114_nation.png'),
  'IRQ': require('../../../assets/nations/115_nation.png'),
  'JPN': require('../../../assets/nations/116_nation.png'),
  'KAZ': require('../../../assets/nations/119_nation.png'),
  'KGZ': require('../../../assets/nations/121_nation.png'),
  'KOR': require('../../../assets/nations/135_nation.png'),
  'KSA': require('../../../assets/nations/133_nation.png'),
  'KUW': require('../../../assets/nations/120_nation.png'),
  'LAO': require('../../../assets/nations/122_nation.png'),
  'LBN': require('../../../assets/nations/123_nation.png'),
  'MAC': require('../../../assets/nations/124_nation.png'),
  'MAS': require('../../../assets/nations/125_nation.png'),
  'MDV': require('../../../assets/nations/126_nation.png'),
  'MNG': require('../../../assets/nations/129505_nation.png'),
  'MSR': require('../../../assets/nations/129520_nation.png'),
  'MYA': require('../../../assets/nations/127_nation.png'),
  'NCL': require('../../../assets/nations/129532_nation.png'),
  'NEP': require('../../../assets/nations/128_nation.png'),
  'OMA': require('../../../assets/nations/130_nation.png'),
  'PAK': require('../../../assets/nations/131_nation.png'),
  'PHI': require('../../../assets/nations/141_nation.png'),
  'PRK': require('../../../assets/nations/129_nation.png'),
  'QAT': require('../../../assets/nations/132_nation.png'),
  'SIN': require('../../../assets/nations/134_nation.png'),
  'SRI': require('../../../assets/nations/136_nation.png'),
  'SSD': require('../../../assets/nations/13113220_nation.png'),
  'SYR': require('../../../assets/nations/137_nation.png'),
  'TCA': require('../../../assets/nations/129526_nation.png'),
  'THA': require('../../../assets/nations/140_nation.png'),
  'TJK': require('../../../assets/nations/139_nation.png'),
  'TKM': require('../../../assets/nations/142_nation.png'),
  'TPE': require('../../../assets/nations/138_nation.png'),
  'VGB': require('../../../assets/nations/129517_nation.png'),
};
