/**
 * Logos der Partner für den Bundler — erzeugt von scripts/generate-partners.js.
 * Nicht von Hand bearbeiten.
 */

export const partnerLogos: Record<string, number> = {
  '2m': require('../../../assets/mediapartner/2M_media.png'),
  '7dimanche': require('../../../assets/mediapartner/7dimanche_media.png'),
  '90-minutos-de-futbol': require('../../../assets/mediapartner/90 Minutos de Fútbol_media.png'),
  'abc': require('../../../assets/mediapartner/ABC_media.png'),
  'abc-deporte': require('../../../assets/mediapartner/ABC Deporte_media.png'),
  'aekfans21': require('../../../assets/mediapartner/AEKfans21_media.png'),
  'aftv': require('../../../assets/mediapartner/AFTV_media.png'),
  'atv-belgium': require('../../../assets/mediapartner/336px-ATV_Belgium_logo.svg_media.png'),
  'avs': require('../../../assets/mediapartner/AVS_logo_media.png'),
  'bet365': require('../../../assets/mediapartner/Bet365_media.png'),
  'betclic': require('../../../assets/mediapartner/Betclic_media.png'),
  'betfan': require('../../../assets/mediapartner/BETFAN_media.png'),
  'betking': require('../../../assets/mediapartner/BetKing_media.png'),
  'betsson': require('../../../assets/mediapartner/Betsson_media.png'),
  'brf': require('../../../assets/mediapartner/512px-BRF_logo.svg_media.png'),
  'bruzz': require('../../../assets/mediapartner/512px-BRUZZ_logo.svg_media.png'),
  'bx1': require('../../../assets/mediapartner/bx1_media.png'),
  'canal-c': require('../../../assets/mediapartner/800px-Canal_C_logo_media.png'),
  'canal-zoom': require('../../../assets/mediapartner/800px-Canal_Zoom_logo_media.png'),
  'celtic-fans-tv': require('../../../assets/mediapartner/Celtic Fans TV_media.png'),
  'celtic-tv': require('../../../assets/mediapartner/Celtic TV_media.png'),
  'clyde-1-superscoreboard': require('../../../assets/mediapartner/Clyde 1 Superscoreboard_media.png'),
  'cnn-indonesia': require('../../../assets/mediapartner/CNN Indonesia_media.png'),
  'cnn-international': require('../../../assets/mediapartner/CNN International_media.png'),
  'cnn-turk': require('../../../assets/mediapartner/CNN Türk_media.png'),
  'danske-spil-oddset': require('../../../assets/mediapartner/Danske Spil Oddset_media.png'),
  'diario-marca': require('../../../assets/mediapartner/Diario MARCA_media.png'),
  'diario-sport': require('../../../assets/mediapartner/Diario Sport_media.png'),
  'el-show-de-ferro': require('../../../assets/mediapartner/El Show De Ferro_media.png'),
  'eleven': require('../../../assets/mediapartner/eleven_media.png'),
  'fanaposten': require('../../../assets/mediapartner/Fanaposten_media.png'),
  'fcb-tv': require('../../../assets/mediapartner/FCB-TV_media.png'),
  'fcz-tv': require('../../../assets/mediapartner/FCZ TV_media.png'),
  'fila': require('../../../assets/mediapartner/Fila_1973_media.png'),
  'focus': require('../../../assets/mediapartner/600px-Focus_logo_media.png'),
  'football-fancast': require('../../../assets/mediapartner/Football Fancast_media.png'),
  'football-fandom': require('../../../assets/mediapartner/Football Fandom_media.png'),
  'fox-deportes-usa': require('../../../assets/mediapartner/FOX Deportes USA_media.png'),
  'fox-radio-chile': require('../../../assets/mediapartner/FOX Radio Chile_media.png'),
  'fox-sports': require('../../../assets/mediapartner/Fox_Sports_2012_media.png'),
  'fox-sports-americas': require('../../../assets/mediapartner/Fox_Sports_Américas_media.png'),
  'fox-tv': require('../../../assets/mediapartner/FOX TV_media.png'),
  'grenz-echo': require('../../../assets/mediapartner/grenz-echo_media.png'),
  'heart-and-hand': require('../../../assets/mediapartner/Heart and Hand_media.png'),
  'hespress': require('../../../assets/mediapartner/Hespress_media.png'),
  'hln': require('../../../assets/mediapartner/hln_media.png'),
  'jako': require('../../../assets/mediapartner/Jako_media.png'),
  'joe': require('../../../assets/mediapartner/JOE_media.png'),
  'kana-sportowy': require('../../../assets/mediapartner/Kanał Sportowy_media.png'),
  'l-avenir': require('../../../assets/mediapartner/l avenir_media.png'),
  'la-libe': require('../../../assets/mediapartner/la libe_media.png'),
  'le-soir': require('../../../assets/mediapartner/le soir_media.png'),
  'marca-tv': require('../../../assets/mediapartner/MARCA TV_media.png'),
  'mls-soccer': require('../../../assets/mediapartner/MLS Soccer_media.png'),
  'nieuwsblad': require('../../../assets/mediapartner/nieuwsblad_media.png'),
  'pandit-football': require('../../../assets/mediapartner/Pandit Football_media.png'),
  'paok-tv': require('../../../assets/mediapartner/PAOK TV_media.png'),
  'play4': require('../../../assets/mediapartner/Play4_2021.svg_media.png'),
  'plays-sports': require('../../../assets/mediapartner/plays sports_media.png'),
  'psv-inside-tv': require('../../../assets/mediapartner/PSV Inside TV_media.png'),
  'psv-tv': require('../../../assets/mediapartner/PSV TV_media.png'),
  'radio-marca': require('../../../assets/mediapartner/Radio MARCA_media.png'),
  'rangers-tv': require('../../../assets/mediapartner/Rangers TV_media.png'),
  'ranks-fc-podcast': require('../../../assets/mediapartner/Ranks FC Podcast_media.png'),
  'ringtv': require('../../../assets/mediapartner/800px-RingTV_logo.svg_media.png'),
  'rmc': require('../../../assets/mediapartner/rmc_media.png'),
  'robtv': require('../../../assets/mediapartner/336px-RobTV_logo.svg_media.png'),
  'rtbf': require('../../../assets/mediapartner/rtbf_media.png'),
  'rtbf-la-une': require('../../../assets/mediapartner/RTBF_La_Une_logo.svg_media.png'),
  'rtc-tele-liege': require('../../../assets/mediapartner/512px-RTC_Télé_Liège_logo.svg_media.png'),
  'rtl': require('../../../assets/mediapartner/rtl_media.png'),
  'rtl-tvi-logo': require('../../../assets/mediapartner/RTL-TVI_Logo_2023.svg_media.png'),
  'rtv': require('../../../assets/mediapartner/600px-RTV_logo_media.png'),
  'scarves-around-the-funnel': require('../../../assets/mediapartner/Scarves Around the Funnel_media.png'),
  'sky-bet': require('../../../assets/mediapartner/Sky_Bet_2020_media.png'),
  'sky-deutschland': require('../../../assets/mediapartner/Sky_Deutschland_2020 copy_media.png'),
  'sky-sports': require('../../../assets/mediapartner/Sky_Sports_2017_media.png'),
  'sky-sports-scotland': require('../../../assets/mediapartner/Sky Sports Scotland_media.png'),
  'sport-cz': require('../../../assets/mediapartner/SPORT.CZ_media.png'),
  'sport-voetbalmagazine': require('../../../assets/mediapartner/sport voetbalmagazine_media.png'),
  'sporz': require('../../../assets/mediapartner/sporz_media.png'),
  'talking-baws': require('../../../assets/mediapartner/Talking Baws_media.png'),
  'telenet-play-sports': require('../../../assets/mediapartner/800px-Telenet_Play_Sports_logo_media.png'),
  'the-calcioland-podcast': require('../../../assets/mediapartner/The Calcioland Podcast_media.png'),
  'the-non-league-football-show': require('../../../assets/mediapartner/The Non League Football Show_media.png'),
  'the-transfer-window-podcast': require('../../../assets/mediapartner/The Transfer Window Podcast_media.png'),
  'the-united-stand': require('../../../assets/mediapartner/The United Stand_media.png'),
  'tvcom-bw': require('../../../assets/mediapartner/TVCOM_BW_logo_actuel_media.png'),
  'tvl-belgium': require('../../../assets/mediapartner/336px-TVL_Belgium_logo.svg_media.png'),
  'tvo-belgium': require('../../../assets/mediapartner/336px-TVO_Belgium_logo.svg_media.png'),
  'u-bet': require('../../../assets/mediapartner/U BET_media.png'),
  'unibet': require('../../../assets/mediapartner/Unibet_media.png'),
  'vans': require('../../../assets/mediapartner/Vans_media.png'),
  'vedia': require('../../../assets/mediapartner/Vedia_logo_media.png'),
  'voetbalkrant': require('../../../assets/mediapartner/voetbalkrant_media.png'),
  'voo': require('../../../assets/mediapartner/VOO_logo.svg_media.png'),
  'vrt-1': require('../../../assets/mediapartner/VRT_1_2023.svg_media.png'),
  'vtm': require('../../../assets/mediapartner/vtm_media.png'),
  'walfoot': require('../../../assets/mediapartner/walfoot_media.png'),
  'websitelogo-lecho': require('../../../assets/mediapartner/websitelogo-lecho_media.png'),
  'willam-hill': require('../../../assets/mediapartner/Willam Hill_media.png'),
};
